/*
 * บัญชีที่นำเข้าจากไฟล์ แอดมิน.xlsx และ ครูที่ปรึกษาทุกห้องเรียน.xlsx
 * หมายเหตุ: เว็บไซต์ static ไม่ควรใช้ไฟล์นี้เป็นระบบความปลอดภัยจริง เพราะ
 * ผู้ที่เปิด DevTools สามารถอ่านข้อมูลได้ ควรย้ายไป Firebase Authentication
 * ก่อนเปิดใช้งานภายนอกอย่างเป็นทางการ.
 */
window.PHANUANG_ACCESS_ACCOUNTS = [
  {username:'44447',passwords:['564'],name:'พีรณัฐ เกตุสวาสดิ์',room:'6/4',role:'student-admin',teams:['หลีด|ดรัม|คัลเลอร์การ์ด']},
  {username:'44348',passwords:['1164'],name:'กฤตยา สินมา',room:'6/4',role:'student-admin',teams:['คัตเอาท์']},
  {username:'44461',passwords:['2464'],name:'ธัญญลักษณ์ กลิ่นเกษร',room:'6/4',role:'student-admin',teams:['บาส(หญิง)','เหรัญญิก']},
  {username:'44334',passwords:['264'],name:'ชัยพร จำนงค์หาญ',room:'6/4',role:'student-admin',teams:['บาส(ชาย)']},
  {username:'46611',passwords:['764'],name:'ธนวัฒน์ มาลัย',room:'6/4',role:'student-admin',teams:['ตะกร้อ']},
  {username:'44766',passwords:['664'],name:'ปัณณทัต วราโภ',room:'6/4',role:'student-admin',teams:['เปตอง']},
  {username:'44363',passwords:['1764'],name:'สุชาดา แผ่ทอง',room:'6/4',role:'student-admin',teams:['วอลเลย์']},
  {username:'44554',passwords:['2964'],name:'ศรัณย์พร ศรีประเสริฐ',room:'6/4',role:'student-admin',teams:['ฟุตซอล']},
  {username:'46612',passwords:['0864','864'],name:'ธีรเทพ ทองประเสริฐ',room:'6/4',role:'student-admin',teams:['ฟุตบอล','ตีกลอง']},
  {username:'44346',passwords:['464'],name:'สุวิจักขณ์ ภู่ชัย',room:'6/4',role:'student-admin',teams:['แบต']},
  {username:'44341',passwords:['364'],name:'ภูเบศ เขตการณ์',room:'6/4',role:'student-admin',teams:['วิ่ง']},
  {username:'44614',passwords:['3064'],name:'กฤติมา ชื่นใจ',room:'6/4',role:'student-admin',teams:['กีฬาประเภทลาน']},
  {username:'44472',passwords:['2764'],name:'ฤทัยรัตน์ จันทร์เกษม',room:'6/4',role:'student-admin',teams:['สวัสดิการ|พยาบาล']},
  {username:'44351',passwords:['1264'],name:'ชลิตา ชูสวัสดิ์',room:'6/4',role:'student-admin',teams:['ประชาสัมพันธ์']},
  {username:'44692',passwords:['1465'],name:'มหาสมุทร ด่านสุขณรงค์',room:'6/5',role:'student-admin',teams:['ขบวน']},
  {username:'46618',passwords:['3765'],name:'จิราวรรณ โพธิ์ขำ',room:'6/5',role:'student-admin',teams:['สแตน']},
  {username:'44400',passwords:['2165'],name:'สุพนิตา ประสายกา',room:'6/5',role:'student-admin',teams:['หลีด|ดรัม|คัลเลอร์การ์ด']},
  {username:'44585',passwords:['2865'],name:'ปิ่นเพชร แสงสวย',room:'6/5',role:'student-admin',teams:['คัตเอาท์']},
  {username:'44456',passwords:['2565'],name:'ฑิตญา บุญพึ่ง',room:'6/5',role:'student-admin',teams:['บาส(หญิง)']},
  {username:'44406',passwords:['465'],name:'คณุตม์พงศ์ ถนอมสัตย์',room:'6/5',role:'student-admin',teams:['บาส(ชาย)']},
  {username:'46619',passwords:['3865'],name:'ศิรภัสสร หนูสุวรรณ',room:'6/5',role:'student-admin',teams:['ตะกร้อ','ตีกลอง']},
  {username:'46613',passwords:['1865'],name:'จริณรัตน์ สืบยุบล',room:'6/5',role:'student-admin',teams:['เปตอง']},
  {username:'44440',passwords:['565'],name:'กิตติภพ เสนาซิว',room:'6/5',role:'student-admin',teams:['วอลเลย์']},
  {username:'44548',passwords:['2765'],name:'ปาลิตา มาลา',room:'6/5',role:'student-admin',teams:['ฟุตซอล']},
  {username:'44446',passwords:['765'],name:'ปัณณวรรธ ตั้งสถิตย์',room:'6/5',role:'student-admin',teams:['ฟุตบอล']},
  {username:'44448',passwords:['865'],name:'ภูวดล ปิยะมิตร',room:'6/5',role:'student-admin',teams:['แบต']},
  {username:'44720',passwords:['1665'],name:'ชนะพล ตรีสุวรรณศานต์',room:'6/5',role:'student-admin',teams:['วิ่ง']},
  {username:'44688',passwords:['1365'],name:'พรพิพัฒน์ นิ่มทอง',room:'6/5',role:'student-admin',teams:['กีฬาประเภทลาน']},
  {username:'46616',passwords:['3565'],name:'กานดา ชำนาญหมอ',room:'6/5',role:'student-admin',teams:['สวัสดิการ|พยาบาล']},
  {username:'44464',passwords:['2665'],name:'นฤกานต์ ร่มโพธิ์',room:'6/5',role:'student-admin',teams:['เหรัญญิก']},
  {username:'44322',passwords:['365'],name:'ภานุพงษ์ ระดับ',room:'6/5',role:'student-admin',teams:['ประชาสัมพันธ์']},
  {username:'69651',passwords:['6501'],name:'ศิวะพัฒน์ โพธิ์ศรี',room:'6/5',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69652',passwords:['6502'],name:'สุพิชฌาย์ นาถสิริวรโชต',room:'6/5',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69641',passwords:['6401'],name:'ทรรศพร พิศรูป',room:'6/4',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69642',passwords:['6402'],name:'นริศ ปืนแก้ว',room:'6/4',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69121',passwords:['5121'],name:'กุนที กลัดสุข',room:'5/12',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69122',passwords:['5122'],name:'อรญา บุญไทย',room:'5/12',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69111',passwords:['5111'],name:'สิริมาส ทองมาดี',room:'5/11',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69112',passwords:['5112'],name:'โยทนัท สงวนโฉม',room:'5/11',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69431',passwords:['4301'],name:'อรุณศรี ศรีชัย',room:'4/3',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69431',passwords:['4302'],name:'พลกฤษณ์ เข็มเพ็ชร',room:'4/3',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69421',passwords:['4201'],name:'ฆ้องชัย คงดี',room:'4/2',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69422',passwords:['4202'],name:'วรรณวิภา สุรเมธสกุล',room:'4/2',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69381',passwords:['3801'],name:'ธารญา ธยาน์ธนาธร',room:'3/8',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69382',passwords:['3802'],name:'กมลวรรณ ทองชื่น',room:'3/8',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69361',passwords:['3601'],name:'ณัฐพล เชยเอม',room:'3/6',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69362',passwords:['3602'],name:'อรรถพล มงคลพร',room:'3/6',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69251',passwords:['2501'],name:'นิพนธ์ เทียนทอง',room:'2/5',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69252',passwords:['2502'],name:'อุดมศักดิ์ วัชระ',room:'2/5',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69211',passwords:['2101'],name:'ดลยา ศรีทองดี',room:'2/1',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69212',passwords:['2102'],name:'เวณิศ ธนาทรัพย์',room:'2/1',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69113',passwords:['1131'],name:'ทิวทอง อ่อนบาง',room:'1/13',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69131',passwords:['1302'],name:'ฤชานนท์ อินอ่วม',room:'1/3',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69132',passwords:['1302'],name:'สุกัญญา คุ้ยทรัพย์',room:'1/3',role:'teacher',teams:['ครูที่ปรึกษา']}
];
window.PHANUANG_ACCESS_DIRECTORY = window.PHANUANG_ACCESS_ACCOUNTS.map(({username,name,room,role,teams}) => ({username,name,room,role,teams}));
