/*
 * บัญชีที่นำเข้าจากไฟล์ แอดมิน.xlsx และ ครูที่ปรึกษาทุกห้องเรียน.xlsx
 * ใช้ระบุเลขประจำตัวผู้ดูแลที่อนุญาต และข้อมูลสำหรับแสดงผลเท่านั้น
 * รหัสผ่านถูกตรวจโดย Firebase Authentication และไม่เก็บในไฟล์สาธารณะนี้.
 */
window.PHANUANG_ACCESS_ACCOUNTS = [
  {username:'44447',name:'พีรณัฐ เกตุสวาสดิ์',room:'6/4',role:'student-admin',teams:['หลีด|ดรัม|คัลเลอร์การ์ด']},
  {username:'44348',name:'กฤตยา สินมา',room:'6/4',role:'student-admin',teams:['คัตเอาท์']},
  {username:'44461',name:'ธัญญลักษณ์ กลิ่นเกษร',room:'6/4',role:'student-admin',teams:['บาส(หญิง)','เหรัญญิก']},
  {username:'44334',name:'ชัยพร จำนงค์หาญ',room:'6/4',role:'student-admin',teams:['บาส(ชาย)']},
  {username:'46611',name:'ธนวัฒน์ มาลัย',room:'6/4',role:'student-admin',teams:['ตะกร้อ']},
  {username:'44766',name:'ปัณณทัต วราโภ',room:'6/4',role:'student-admin',teams:['เปตอง']},
  {username:'44363',name:'สุชาดา แผ่ทอง',room:'6/4',role:'student-admin',teams:['วอลเลย์']},
  {username:'44554',name:'ศรัณย์พร ศรีประเสริฐ',room:'6/4',role:'student-admin',teams:['ฟุตซอล']},
  {username:'46612',name:'ธีรเทพ ทองประเสริฐ',room:'6/4',role:'student-admin',teams:['ฟุตบอล','ตีกลอง']},
  {username:'44346',name:'สุวิจักขณ์ ภู่ชัย',room:'6/4',role:'student-admin',teams:['แบต']},
  {username:'44341',name:'ภูเบศ เขตการณ์',room:'6/4',role:'student-admin',teams:['วิ่ง']},
  {username:'44614',name:'กฤติมา ชื่นใจ',room:'6/4',role:'student-admin',teams:['กีฬาประเภทลาน']},
  {username:'44472',name:'ฤทัยรัตน์ จันทร์เกษม',room:'6/4',role:'student-admin',teams:['สวัสดิการ|พยาบาล']},
  {username:'44351',name:'ชลิตา ชูสวัสดิ์',room:'6/4',role:'student-admin',teams:['ประชาสัมพันธ์']},
  {username:'44319',name:'นราธร เหมือนเอี่ยม',room:'6/5',role:'student-admin',teams:['ADMIN']},
  {username:'44692',name:'มหาสมุทร ด่านสุขณรงค์',room:'6/5',role:'student-admin',teams:['ขบวน']},
  {username:'46618',name:'จิราวรรณ โพธิ์ขำ',room:'6/5',role:'student-admin',teams:['สแตน']},
  {username:'44400',name:'สุพนิตา ประสายกา',room:'6/5',role:'student-admin',teams:['หลีด|ดรัม|คัลเลอร์การ์ด']},
  {username:'44585',name:'ปิ่นเพชร แสงสวย',room:'6/5',role:'student-admin',teams:['คัตเอาท์']},
  {username:'44456',name:'ฑิตญา บุญพึ่ง',room:'6/5',role:'student-admin',teams:['บาส(หญิง)']},
  {username:'44406',name:'คณุตม์พงศ์ ถนอมสัตย์',room:'6/5',role:'student-admin',teams:['บาส(ชาย)']},
  {username:'46619',name:'ศิรภัสสร หนูสุวรรณ',room:'6/5',role:'student-admin',teams:['ตะกร้อ','ตีกลอง']},
  {username:'46613',name:'จริณรัตน์ สืบยุบล',room:'6/5',role:'student-admin',teams:['เปตอง']},
  {username:'44440',name:'กิตติภพ เสนาซิว',room:'6/5',role:'student-admin',teams:['วอลเลย์']},
  {username:'44548',name:'ปาลิตา มาลา',room:'6/5',role:'student-admin',teams:['ฟุตซอล']},
  {username:'44446',name:'ปัณณวรรธ ตั้งสถิตย์',room:'6/5',role:'student-admin',teams:['ฟุตบอล']},
  {username:'44448',name:'ภูวดล ปิยะมิตร',room:'6/5',role:'student-admin',teams:['แบต']},
  {username:'44720',name:'ชนะพล ตรีสุวรรณศานต์',room:'6/5',role:'student-admin',teams:['วิ่ง']},
  {username:'44688',name:'พรพิพัฒน์ นิ่มทอง',room:'6/5',role:'student-admin',teams:['กีฬาประเภทลาน']},
  {username:'46616',name:'กานดา ชำนาญหมอ',room:'6/5',role:'student-admin',teams:['สวัสดิการ|พยาบาล']},
  {username:'44464',name:'นฤกานต์ ร่มโพธิ์',room:'6/5',role:'student-admin',teams:['เหรัญญิก']},
  {username:'44322',name:'ภานุพงษ์ ระดับ',room:'6/5',role:'student-admin',teams:['ประชาสัมพันธ์']},
  {username:'69651',name:'ศิวะพัฒน์ โพธิ์ศรี',room:'6/5',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69652',name:'สุพิชฌาย์ นาถสิริวรโชต',room:'6/5',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69641',name:'ทรรศพร พิศรูป',room:'6/4',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69642',name:'นริศ ปืนแก้ว',room:'6/4',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69121',name:'กุนที กลัดสุข',room:'5/12',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69122',name:'อรญา บุญไทย',room:'5/12',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69111',name:'สิริมาส ทองมาดี',room:'5/11',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69112',name:'โยทนัท สงวนโฉม',room:'5/11',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69431',name:'อรุณศรี ศรีชัย',room:'4/3',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69432',name:'พลกฤษณ์ เข็มเพ็ชร',room:'4/3',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69421',name:'ฆ้องชัย คงดี',room:'4/2',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69422',name:'วรรณวิภา สุรเมธสกุล',room:'4/2',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69381',name:'ธารญา ธยาน์ธนาธร',room:'3/8',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69382',name:'กมลวรรณ ทองชื่น',room:'3/8',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69361',name:'ณัฐพล เชยเอม',room:'3/6',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69362',name:'อรรถพล มงคลพร',room:'3/6',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69251',name:'นิพนธ์ เทียนทอง',room:'2/5',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69252',name:'อุดมศักดิ์ วัชระ',room:'2/5',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69211',name:'ดลยา ศรีทองดี',room:'2/1',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69212',name:'เวณิศ ธนาทรัพย์',room:'2/1',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69113',name:'ทิวทอง อ่อนบาง',room:'1/13',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69131',name:'ฤชานนท์ อินอ่วม',room:'1/3',role:'teacher',teams:['ครูที่ปรึกษา']},
  {username:'69132',name:'สุกัญญา คุ้ยทรัพย์',room:'1/3',role:'teacher',teams:['ครูที่ปรึกษา']}
];
window.PHANUANG_ACCESS_DIRECTORY = window.PHANUANG_ACCESS_ACCOUNTS.map(({username,name,room,role,teams}) => ({username,name,room,role,teams}));
